### ISSUE TITLE
Encontro em Setembro - 8º Encontro de Haskellers de São Paulo (?)

### ISSUE THREAD

**Issue by yamadapc** [haskellbr/meetups#1]
- [x] Decidir um assunto
  - (@yamadapc: por mim seria um hands-on; dojo ou workshop)
- [x] Encontrar um local
- [x] Preparar o conteúdo
- [x] Divulgar
- [ ] Se divertir pacas

**Comment by hannelita** [comment]
- [ ] Sábado

**Comment by ghost** [comment]
Acho que um hands-on seria bem massa!

Pergunta: rolaria fazer o encontro em uma sexta / fds? Durante a semana é meio complicado sair do trampo e chegar no horário ):

**Comment by yamadapc** [comment]
:+1: Hands-on no sábado - 3-4h de duração

---

Nesse caso:
- O que fazer?
  - "Traga seu pet-project" (difícil de divulgar IMO)
  - Estabelecer algo a ensinar
  - Estabelecer alguns projetos para os quais contribuir

**Comment by ghost** [comment]
Hmm, gosto bastante da ideia de pegar um ou mais projetos para contribuir (y)

**Comment by yamadapc** [comment]
Eu gosto bastante da ideia; certamente dá pra fechar ou encaminhar issues em projetos populares. Mas precisaríamos planejar um pouco como fazer isso. Precisa de tipo 1 pessoa que saiba Haskell para cada 3-5 pessoas que não façam ideia do que se trata e coisas assim.

Se fossemos fazer isso precisaríamos escolher os projetos e dar uma olhada nas issues atacáveis antes do encontro.

---

Acho que são todas coisas válidas. Também uma não exclue a outra; supondo que tenhamos uma ferramenta para dar workshops, poderíamos fazer os dois ao mesmo tempo.

---

Preciso fazer um sprint para terminar o workhs.

**Comment by yamadapc** [comment]
http://www.meetup.com/haskellbr-sp/events/233395066/
